---
database:
  # PGObserver database
  name: pgobserver
  host: localhost
  port: 5432

  # frontend credentials for PGObserver database
  frontend_user: pgobserver_frontend
  frontend_password: pgobserver_frontend


influxdb:
  host: localhost
  port: 8086
  username: root
  password: root
  database: pgobserver
  max_days_to_fetch: 7      # how much old data to fetch when starting up
  data_model_pure: True     # Influx 0.8 default, e.g. load.db1
  data_model_tag: False     # Influx 0.9 default e.g. load, dbname=db1 (dbname is a tag)
                            # if both are chosen data is duplicated. 0.8 way is mostly a lot faster but
                            # Grafana editor doesn't support it anymore so one needs to handwrite queries
  tag_mode_series_prefix:   tag_

max_worker_threads: 5

data_collection_queries_to_process:
    - avg_query_runtime_per_db
    - avg_sproc_runtime_per_db
    - avg_sproc_runtime_per_schema
    - blocked_process_counts
    - db_general_info
    - db_size
    #- index_details  # leaving out by default, very rarely needed
    - load
    - scan_and_iud_rates_per_db
    - scan_and_iud_rates_per_schema
    - sproc_details_per_schema_sproc
    - table_and_index_sizes_per_schema
    - table_details
    #- table_io_details # leaving out by default, very rarely needed
